name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Build.
      run: docker build -t twitchax/nordvpn-proxy .