name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout!
      uses: actions/checkout@v1
    - name: Build.
      run: docker build -t twitchax/nordvpn-proxy .
    - name: Docker login.
      run: echo ${{DOCKER_PASSWORD}} | docker login --username ${{DOCKER_USERNAME}} --password-stdin
    - name: Docker push.
      run: docker push twitchax/nordvpn-proxy